### ISSUE TITLE
R Dev Guide 

### ISSUE THREAD

**Issue by MayaGans** [forwards/rcontribution#1]
Create an [R Developer Guide](https://github.com/forwards/rdevguide) to be hosted on the Forwards website initially, and eventually publish on the R project website when it has reached a useful state.

**Comment by hturner** [comment]
Thanks Maya! Yes, we have already made a small start on this within the Forwards On-ramps team, but it would benefit from more contributors (both experienced and novice), so hopefully this can become part of the wider initiative with R core and other folks from the R community. 

We are using the [Python Dev Guide](https://devguide.python.org) as template - some parts will be easier to fill in than others for R development, but I think creating something useful (maybe a subset of the current sections) could be done by the end of the year, hence labelling this as a short-term goal.

**Comment by hturner** [comment]
As mentioned in #2, @SaranjeetKaur has been funded to work on this project for 12 weeks, starting 22 Feb 2021. Although Saranjeet will lead the effort during this time, it will still be important to get input from a wide group, from novice to experienced contributors.

In particular, it will still be helpful to have notes on installing R, as @MayaGans proposed in forwards/rdevguide#1, so I'll add the start date of Saranjeet's project as a date to aim for on that issue.

**Comment by hturner** [comment]
I think we can close this as we have reached the initial goal of creating a draft version on the Forwards website: https://forwards.github.io/rdevguide/. Currently the guide covers identifying, reporting and reviewing bugs; preparing and submitting a patch; contributing to documentation, and testing pre-release versions of R. It also includes some technical help (building and installing R-devel on Windows, developer tools) and some community orientation (list of R core developers/contributors, where to get help and keep up-to-date with R project news). 

Further work on the guide (especially now Saranjeet's project has ended) can be defined in specific issues on https://github.com/forwards/rdevguide, or as new issues on this repo if part of a wider initiative.
