### ISSUE TITLE
Governance of the R Contribution Working Group (RCWG)

### ISSUE THREAD

**Issue by SaranjeetKaur** [forwards/rcontribution#10]
Perhaps a Steering Committee can be set up for the smooth functioning of the RCWG.

**Comment by hturner** [comment]
A steering committee seems over-complicated for a working group. I would say the R core members that attend act as the senior stakeholders or experts.

That's not to say that we shouldn't consider the governance of the working group though. I guess I am the de facto leader as the one that got the working group off the ground. I enlisted @nzgwynn and @karawoo as links to MiR and R-Ladies respectively - we might want to formalize this a bit more into a leadership team. Not sure what they/others link about that, or if there are other things we could do to improve governance of the group.

**Comment by nzgwynn** [comment]
I agree that a steering committee seems over-complicated. I prefer flat management to anything hierarchical.

**Comment by hturner** [comment]
View of WG at September meeting in line with comments above (R Core/R Foundation provide steering for the group, flat structure is working okay for now). So closing this issue.
