### ISSUE TITLE
Apply for Tweag Fall 2020 Fellowship

### ISSUE THREAD

**Issue by SaranjeetKaur** [forwards/rcontribution#2]
Tweag are offering 12-week funded fellowships to support contributions to open source projects, see the [announcement on their blog](https://www.tweag.io/blog/2020-07-28-os-fellowship/).

As stated in the [full details](https://boards.greenhouse.io/tweag/jobs/4638654002), they are encouraging applications from underrepresented communities: "We explicitly invite applications from populations underrepresented within computer science".

Tweag have done R-related work before: see [HaskellR](https://tweag.github.io/HaskellR/) and the associated [blog](https://www.tweag.io/blog/2017-07-10-haskell-r-best-both-worlds/) about it, so perhaps they might be interested in an R-related proposal.

I am interested in applying myself and can work on a proposal during September’20. It would be great if I get some guidance on the kind of project I can propose here. Possibly we could submit more than one proposal, if others are interested. The ideas can fall in many broad categories as they state in the [announcement](https://www.tweag.io/blog/2020-07-28-os-fellowship/) "The contribution needn’t just be code: We’re also open to supporting research, tutorials, documentation, design specifications, etc.”

**Comment by lauracion** [comment]
Very interesting, Saranjeet! Maybe if you share this issue in R-Ladies Slacks you will find more people interested? 😸

**Comment by SaranjeetKaur** [comment]
Shared!

**Comment by hturner** [comment]
Good news: although the application for a Tweag fellowship was not successful, the R Foundation have agreed to fund @SaranjeetKaur's proposal, which was to work on an initial draft of the [R dev guide](https://github.com/forwards/rdevguide). Several members of R core expressed an interest in supporting the project; @lawremi and I will act as supervisors. The planned start date is 22 Feb 2021, after Saranjeet finishes her MPhil.
