### ISSUE TITLE
Create a supportive online space to foster contributor community

### ISSUE THREAD

**Issue by hturner** [forwards/rcontribution#5]
Currently, we have a few venues for discussion

- R-devel: seen as daunting/unfriendly by new contributors, designed for Q&A vs mentoring/building community
- R-Ladies/Forwards slack: okay for people that are there, but not open to all

It would be good to have something similar to the r4ds slack, that is designed for more experienced folk to support learners, that is focused on the developer community (focusing on R core contributors in the first instance). We can use it to discuss our initiatives and also use it as a place to mentor people that are trying to contribute.

We could use Slack - many R communities already do - but we might consider Zulip, which has a few advantages in this case:
 - Open source: R core members/other experienced collaborators may be more willing to use
 - Threading: threads are created for each topic, which may make it better for discussing technical issues
 - Easy to join and sign in with email/GitHub/GitLab/Google account.
 - Posting guide and code of conduct can be put upfront, e.g. https://python.zulipchat.com/login/

We should be eligible for a free hosted version if it is set up as an R project or Forwards space: https://zulipchat.com/for/open-source/.

**Comment by hturner** [comment]
I forgot to say, a key step would be putting a code of conduct in place. I think we could lightly revise the useR! one (https://www.r-project.org/coc.html) to be suitable for an online forum like this.

As for a posting guide, we might borrow some ideas from the mentorship code of conduct here: https://www.python.org/dev/core-mentorship/.

Hopefully, we would not get too tied up in this, so we can get a mentorship forum up and running by the end of the year.

**Comment by lauracion** [comment]
My two cents about this are that I have seen several (R) community-led efforts working very successfully using a combination of Slack and GitHub issues. Slack is used for the more dynamic discussions for which there is no need to keep a long-term and ordered record, while GitHub is used to move from talking to doing and keep more permanent stuff.  

As for asking for help, particularly for novices, I have seen Slack being a lot more approachable both because it allows chats among small groups or direct messages and different levels of privacy. Having active experts in that Slack that are willing to help is a highly necessary ingredient. 

With all its caveats, I think it is fair to say Slack is still the most widely used tool and a lot of people don´t want to add yet another communication tool. 

Imo, it would be great to have a Slack for communication between meetings in addition to this repo while we come to an agreement of a more permanent solution.

**Comment by jtr13** [comment]
Agree that Slack would work well for the discussion. In terms of the archive, it may sufficient for Forwards to have a paid account to keep the archive--not every participant needs to. I like the idea of moving particular items to another place so they are easily accessible. In short, there's no way around some human curation of discussion material unless you have really strict rules about what you can post and people who enforce those rules, which is exactly the type of atmosphere we are trying to avoid.

**Comment by MichaelChirico** [comment]
As an example of another dev community working with Slack for similar ends I came across the Presto community Slack today:

https://prestosql.io/slack.html

**Comment by hturner** [comment]
From the discussion here and at our last meeting, it seems there is more enthusiasm for using Slack. In general, I agree it works well for fostering community and I think the free version is fine for this purpose. However, if another platform meant we got more engagement from R core/experienced contributors, I think it would be worth using a separate tool.

I have written a short survey so we can collect some data on this and make an informed decision. Since Q&A-type platforms (Discourse, Biostar) were also discussed as a potential alternative/supplement, we can collect data on this at the same time. I will share a link in the team chat for people to preview/test before I circulate more widely.

**Comment by hturner** [comment]
Following the [results of the survey](https://github.com/forwards/rcontribution/blob/master/mentorship/chat_and_q_and_a_platforms_survey.md) that were discussed at the team meeting in October, I've created a Slack workspace. I've put an invite link in the agenda for the November meeting so those currently involved can kick-start the group - please join!

I've also drafted a code of conduct, which I've put in a pull request (#8 ) so that you can review and comment. Once we've got going we can create a landing page on the Forwards/R-project website with the coc and a Join button, and start encouraging a wider group to join.

**Comment by hturner** [comment]
I've created an R Contribution site using GitHub pages (so it appears as a subsite of the Forwards website: https://forwards.github.io/rcontribution/). As well as the coc and join button, it also gives a bit of information about the working group and links back to this repo. The webpage is live, but not linked/advertised anywhere yet, so we can do a soft launch inviting people we think might be interested, allowing time for feedback and for the Slack to get more active.

@karawoo and @spcanelon have agreed to join me as admins for 2021, so we're all good to go!

**Comment by hturner** [comment]
The R-Devel Slack is now up and running: https://forwards.github.io/rcontribution/slack.
