### ISSUE TITLE
Apply to the Better Scientific Software (BSSw) Fellowship Program (deadline 30 Sept)

### ISSUE THREAD

**Issue by 3mmaRand** [forwards/rcontribution#7]
Hi All, Would the On-ramps team have activities that need money?
The Better Scientific Software (BSSw) Fellowship Program is open (deadline 30 Sept). It gives recognition and funding to leaders and advocates of high-quality scientific software. Funding is up to $25,000 to promote better scientific software. Applicants have to be US based and able to receive funding from the U.S. Department of Energy (U.S. government labs, U.S. universities, and U.S.-based corporations.)
An application based round:

- Contributing to R Core is difficult and limited to relatively few
- increasing diverse community contribution improves software quality
- therefore increasing diversity of R Core contributes promotes good software

would work. A previous successful application was to Damian Rouson of the Sustainable Horizons Institute ([http://shinstitute.org/about/mission/](http://shinstitute.org/about/mission/)):  "Agile scientific software development integrated with expanding outreach to underrepresented groups"
[https://bssw.io/pages/bssw-fellowship-program](https://bssw.io/pages/bssw-fellowship-program)

I'm not eligible but I am a UK Software Sustainability Fellow (the fellowship programme was the model for the BSSw fellowship programme) and would be happy to contribute/give feedback on an application.
The application itself is not too onerous (honest!)

If On-ramps couldn't make use of this programme, the teaching team will apply for giving workshops if we have an eligible person to act as the applicant. It would be good to have a decision on that at the 8 September meeting.

**Comment by lawremi** [comment]
This is a great resource, thanks for bringing it to our attention. We'll discuss it at our meeting next week.

**Comment by hturner** [comment]
We don't have a candidate/idea for this fellowship for this round, so please explore this as an option for the teaching team!
