### ISSUE TITLE
R Contribution Working Group in LatinR 2021 (and beyond)?

### ISSUE THREAD

**Issue by yabellini** [forwards/rcontribution#9]
I am one of the LatinR chairs that will take place during the week of November 10, 2021, in virtual format.
We would very much like the work of this group to be featured.  

## General goals

* As a regional conference, we would like to highlight group members from our region and/or who can speak in Spanish or Portuguese and cal told us about this group.
* We would also like to publicize and bring resources closer so that more people from our region can participate and contribute.
* We don't need (and I don't think we can) to do all of these potential alternatives this year, but I let this here because can be good ideas for the next editions.

### Guest talks

We think a talk presenting the R Dev Guide is a very good topic.  We would love Saranjeet can deliver the talk.  We think that a good strategy can be if she can record the talk in English in advance, so we can translate subtitles to Spanish and Saranjeet can be there online while we play the video for the Q&A session. 

bugRzilla by Lluís.

We could find out if any R Core members speak Spanish/Portuguese. We will be very happy if some Core Team members want to deliver a talk also in English.

### Panels

Memeber of this team that speak Spanish and can told about this group. 

### Tutorials

LatinR has a full week for tutorials previous to the conferences.  All of them are free and we run them jointly with R-Ladies chapters and regional RUGs.

Re-run the Contributing to R and/or Translating R to you Language tutorials at LatinR (presumably focusing on Spanish and Portuguese in the second case).

**Comment by llrs** [comment]
Depending on the hour I could talk about my small contribution to the working group. Those days I have another conference but feel free to ping or reach me via any other way if you want me to talk a bit.

**Comment by gmbecker** [comment]
I can give a talk if desired and/or rerun the tutorial. It does work better
with a co-presenter from r-core imo, but I cannot volunteer them.

I think the tutorial went quite well though and wouldn't need much or any
updating to what we ran for user.

I'm not fluent in any languages other than English, though. Sorry.

**Comment by SaranjeetKaur** [comment]
Thank you for this @yabellini! Glad to present a talk at LatinR 2021!

**Comment by yabellini** [comment]
Thank you all for your answers!!  I will contact all you on the Slack for more details.

**Comment by llrs** [comment]
@yabellini I finally got confirmation that my talk on the conference that overlapped with latinR will be the 9th November. Any other day later that week I'm available (if the time difference allows it :)

**Comment by yabellini** [comment]
Great Lluis, thank you so much!

**Comment by hturner** [comment]
Closing now LatinR over, we can open new issues for any follow-on ideas/initiatives.
